---
# SLURM BwUniCluster2.0
name: "SLURM"  # MUST BE "SLURM"
job-name: "door_open_task_experiment"  # this will be the experiment's name in slurm
partition: "single"
num_parallel_jobs: 100  # max number of jobs executed in parallel
ntasks: 1  # leave that like it is
cpus-per-task: 1
mem-per-cpu: 4000
time: 4320  # in minutes

---
name: "door_open_ddpg_experiment"
path: "outcomes/cluster/door_open_task"
repetitions: 20

params:
  total_steps: 5_000_000
  env_name: "DoorOpenEnv-v27"
  algorithm: "DDPG"

---
name: "door_open_td3_experiment"
path: "outcomes/cluster/door_open_task"
repetitions: 20

params:
  total_steps: 5_000_000
  env_name: "DoorOpenEnv-v27"
  algorithm: "TD3"